#!/bin/bash

python3_versions="$(py3versions -s 2> /dev/null)"

cp -a "tests" "tox.ini" "${AUTOPKGTEST_TMP}"
cd "${AUTOPKGTEST_TMP}"
ln -s /usr/lib/python3/dist-packages/blessed blessed

for python3 in $python3_versions; do
    $python3 -m pytest -v -x -rs || exit 1
done
